### ISSUE TITLE
Prism.js breaks menu toggle on IE9-11.

### ISSUE THREAD

**Issue by mandalatv** [fbrctr/fabricator#153] opened 2015-07-25 15:16 UTC
When viewing my Fabricator instance in IE the menu is suppressed and won't toggle. I wasn't seeing any JS console errors. 

I've found that downloading the default development version here: [http://prismjs.com/download.html] (http://prismjs.com/download.html) and replacing src/assets/fabricator/scripts/prism.js restores functionality.

**Comment by LukeAskew** [comment] 2015-07-27 12:52
I believe this is a duplicate of #142 and is fixed by #149.

New release coming soon.

**Closed by LukeAskew** 2015-07-27 12:52 UTC

**Comment by ericwisehammer** [comment] 2017-11-22 18:29
Hey there,

I don't mean to gravedig on this but I can confirm the newest version of Fabricator has this issue in IE11 and the same resolution proposed by @mandalatv still successfully resolves it.
